In [19]:
import pandas as pd
from datetime import datetime, timedelta

from facebook_scraper import get_posts

import smtplib, ssl
import mimetypes
from email.mime.multipart import MIMEMultipart
from email import encoders
from email.message import Message
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.text import MIMEText

import pywhatkit
import time

In [21]:

url = []
text = []
date = []
comments = []
likes = []
user = []

interests = ['סנטר', 'צפון ישן', 'הצפון הישן', 'שלושה חדרים', '3 חדרים',
             'שני שותפים', '2 שותפים', 'בוגרשוב', 'כיכר', 'לב העיר', 'רבין', 'פרישמן', 'גורדון']
ignore = ['מכירה', 'למכירה','להחלפה']

groupNames = ['287564448778602', 'telavivrentals', 'ApartmentsTelAviv', '101875683484689', 'telavivroommates', '35819517694', '458499457501175', 'dirotTA', '2092819334342645',
              '2065942027026008', 'emptyLiveableTLVapartments', '1196843027043598', '733810383372996', '676960712363338', '485208978351445', '453182374868551', '429827780505313', 'TelAvivApartments']

prevFile = pd.read_csv("./results.csv") 
prevURLS = prevFile['link'].unique()

for i in groupNames:
    for post in get_posts(group=i, pages=10, options={"posts_per_page": 50, "allow_extra_requests": False}):
        if post['post_text'] == None:
            continue
        if any(words in post['post_text'] for words in interests):
            if any(words in post['post_text'] for words in ignore):
                continue
            postURL = post['post_url'].replace("https://m.", "https://", 1)
            if postURL in prevURLS:
                print("skipped URL "+ postURL)
           #     continue
            text.append(post['post_text'][:200])
            url.append(postURL)
            date.append(post['time'])
            comments.append(post['comments'])
            likes.append(post['likes'])
            user.append(post['username'])

print("Finished parsing facebook results")

if len(date) == 0:
    print("no data for file")
    exit()
    
data = {
    'date': date,
    'link': url,
    'info': text,
    'username': user,
    '#comments': comments,
    '#likes': likes
}

df = pd.DataFrame.from_dict(data, orient='index')
df = df.transpose()
today = pd.to_datetime(datetime.now())
threeDaysAgo = pd.to_datetime(datetime.today() - timedelta(hours=5))
df = df.loc[(df['date'] > threeDaysAgo) & (df['date'] < datetime.now())]
df = df.sort_values('date', ascending=False)
df.dropna
df = df.drop_duplicates(subset='info')
df.to_csv('./results.csv', index=False, encoding='utf-8-sig')

C:\Users\Assaf\anaconda3\lib\site-packages\dateparser\freshness_date_parser.py:76: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  now = self.get_local_tz().localize(now)
C:\Users\Assaf\anaconda3\lib\site-packages\dateparser\date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)

,date,link,info,username,#comments,#likes
0,2022-06-27 17:09:23,https://facebook.com/groups/287564448778602/pe...,להשכרה מתיווך\nדירת 3 חדרים בצפון החדש\nרחוב ג...,Daniel Lidor,2,1
1,2022-06-27 19:35:37,https://facebook.com/groups/287564448778602/pe...,דירת 3 חדרים להשכרה במידטאון.\nקומה 29 עם חניה...,Karin Gershkovich Lipskin,6,1
2,2022-06-27 09:49:31,https://facebook.com/groups/287564448778602/pe...,דירת 3.5 חדרים עם חנייה - צפון ישן.\n\nברחוב ל...,Si Alkobi,9,2
3,2022-06-27 14:06:31,https://facebook.com/groups/287564448778602/pe...,** להשכרה 3 חדרים ארלוזורוב 17 - צפון הישן תל ...,Sagi Property,9,2
4,2022-06-27 18:25:14,https://facebook.com/groups/287564448778602/pe...,"להשכרה מתיווך\nדירת 3 חדרים גדולה 88 מ""ר\nבצפו...",Or Shani,1,0
...,...,...,...,...,...,...
326,2022-06-27 09:50:33,https://facebook.com/groups/TelAvivApartments/...,דירת 3.5 חדרים עם חנייה - צפון ישן.\n\nברחוב ל...,Si Alkobi,0,0
327,2022-06-24 14:05:13,https://facebook.com/groups/TelAvivApartments/...,Subletting our apartment in Rabin Square from ...,Ziv Itzkovich,0,0
328,2022-06-26 19:06:44,https://facebook.com/groups/TelAvivApartments/...,להשכרה בלב העיר ממש צמוד לכיכר המדינה דירת 2.5...,Yossi Cohen,0,0
329,2022-06-26 17:17:03,https://facebook.com/groups/TelAvivApartments/...,🛑 SHOWING MONDAY 🛑\nENGLISH DESCRIPTION BELOW ...,Megane Bhayoun,0,0
330,2022-06-26 16:15:49,https://facebook.com/groups/TelAvivApartments/...,"3 חדרים מרווחות וחדשות להשכרה בדרום ת''א, מרפס...",ספייס ברוקרס,0,0

In [17]:
def sendWhatsapp():
    print("sending whatsapp")
    try:
        send_time = datetime.now()
        send_time_hour = int(send_time.strftime("%H"))
        send_time_min = int(send_time.strftime("%M"))
        NUMBER = "<INSERT YOUR PHONE NUMBER AS STRING INCLUDING COUNTRY CODE (+XYZ...)>"
        msg = "Appartments:\n\n" + "\n""\n".join(df['link'].unique())
        # sending message to receiver
        #pywhatkit.sendwhatmsg(NUMBER,
        #                      random_sentence,
        #                      send_time_hour, send_time_min, tab_close=True)

        pywhatkit.sendwhatmsg_instantly(NUMBER, msg, tab_close = True)
#         pyautogui.moveTo(screen_width * 0.694, screen_height* 0.964) # Moves the cursor the the message bar in Whatsapp
#         pyautogui.click() # Clicks the bar

#         pyautogui.press('enter') # Sends the message
        print("Successfully Sent!")
    except:
        # handling exception
        # and printing error message
        print("An Unexpected Error!")

,date,link,info,username,#comments,#likes
0,2022-06-27 17:52:05,https://facebook.com/groups/287564448778602/pe...,❗❗להשכרה דירת 3 חדרים ו-2 מרפסות בשכונת פלורנט...,Lidar Alon,0,0
6,2022-06-27 17:24:48,https://facebook.com/groups/287564448778602/pe...,⭐⭐להשכרה מרוקח נכסים⭐\n\nדירת 3 חדרים שותפים/מ...,Yaron Rokah,0,0
47,2022-06-27 17:23:40,https://facebook.com/groups/telavivrentals/per...,⭐⭐להשכרה מרוקח נכסים⭐\n\nדירת 3 חדרים שותפים/מ...,Yaron Rokah,0,0
7,2022-06-27 17:15:25,https://facebook.com/groups/287564448778602/pe...,⭐⭐להשכרה מרוקח נכסים⭐\n\nדירת 3 חדרים בלב העיר...,Yaron Rokah,0,0
8,2022-06-27 17:11:28,https://facebook.com/groups/287564448778602/pe...,⭐⭐להשכרה מרוקח נכסים⭐⭐\n🏠דירת 3 חדרים ל2 שותפי...,Yaron Rokah,0,0
...,...,...,...,...,...,...
281,2022-06-24 19:05:39,https://facebook.com/groups/733810383372996/pe...,שלום לכולם 🙂\nמחפשת שותפ/ה לדירת 3 חדרים שווה ...,קרין מגן צלמת,0,0
214,2022-06-24 19:04:39,https://facebook.com/groups/2092819334342645/p...,שלום לכולם 🙂\nמחפשת שותפ/ה לדירת 3 חדרים שווה ...,קרין מגן צלמת,0,0
282,2022-06-24 19:01:16,https://facebook.com/groups/733810383372996/pe...,"היי היי לכם ,אחרי שנתיים וחצי בדירה שהייתה לי ...",Noa Tanne,0,0
109,2022-06-24 18:56:08,https://facebook.com/groups/ApartmentsTelAviv/...,שלום לכולם 🙂\nמחפשת שותפ/ה לדירת 3 חדרים שווה ...,קרין מגן צלמת,0,1
176,2022-06-24 18:55:01,https://facebook.com/groups/458499457501175/pe...,שלום לכולם 🙂\nמחפשת שותפ/ה לדירת 3 חדרים שווה ...,קרין מגן צלמת,0,1

### For sending Email

In [13]:
sendWhatsapp()

sending email
sent email